### ISSUE TITLE
Consider merge to nock, and nock to flatiron.

### ISSUE THREAD

**Issue by heapwolf** [nodejitsu/mock-request#4]
Let's consider bringing @pgte's `nock` (https://github.com/pgte/nock) into flatiron in favor of this project and merging any features from this project into `nock`.

**Comment by indexzero** [comment]
Not opposed to this, although there doesn't seem to be anything in this library worth porting. @pgte I have some reservations about overwriting `http.request`. Not in-so-far that I disagree with it, but that it's not 100% mocked. 

All it takes is one smart-ass library author (or ancient library) to use `http.createClient` or instantiate `http.ClientRequest` directly. This circumvents nock. 

Would you be open to overriding `http.ClientRequest` instead?

**Comment by pgte** [comment]
@indexzero Yup, no problem, fortunately http.ClientRequest is exposed. I opened this issue: https://github.com/pgte/nock/issues/26

**Comment by xla** [comment]
Only to add some thoughts from the [nodejs-dev google group](http://groups.google.com/group/nodejs-dev) where it's [stated](http://groups.google.com/group/nodejs-dev/browse_thread/thread/f3c277cbb32cc776) that bare constructors will likely go away in the future and which would leave us with factories and the intended interfaces.

**Comment by indexzero** [comment]
@goldjunge I don't take away that point from the discussion at all: felixge, mikeal, polotek, and piscisaureus were all for it. That's a pretty solid list of +1s

**Comment by pgte** [comment]
@indexzero @hij1nx I recently finished a big refactoring of nock and http.ClientRequest overriding is included. It now contains 91 client tests (awesome 8 contributors).

**Comment by heapwolf** [comment]
w00t! Let's drop it into flatiron! Just transfer it from the admin page whenever you're ready. And then we can just delete this repo.

**Comment by indexzero** [comment]
@pgte @hij1nx Sounds good. We shouldn't straight up delete this repository for a couple of months though. A deprecation warning and redirect to `nock` will help transition anyone using this.

**Comment by heapwolf** [comment]
Agreed, closing issue.

**Comment by pgte** [comment]
@hij1nx I don't have write access to the flatiron org. How do you want to do this?

**Comment by bithavoc** [comment]
How about adding a disclaimer in the readme? "We recommend you to use Nock instead" or something.

**Comment by indexzero** [comment]
Added deprecation notice. Closing.
